# Generated by Django 6.0.1 on 2026-01-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPrayerTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('day', models.CharField(max_length=16)),
                ('hijri', models.CharField(blank=True, max_length=64)),
                ('fajr', models.CharField(blank=True, max_length=8)),
                ('sunrise', models.CharField(blank=True, max_length=8)),
                ('dhuhr', models.CharField(blank=True, max_length=8)),
                ('asr', models.CharField(blank=True, max_length=8)),
                ('maghrib', models.CharField(blank=True, max_length=8)),
                ('isha', models.CharField(blank=True, max_length=8)),
                ('comments', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
